### ISSUE TITLE
RandomGeneratorTest occasionaly fails

### ISSUE THREAD

**Issue by shivkumaryadav** [CJSCommonPlatform/test-utils#28]
java.lang.AssertionError: failed on attempt 4420 for value 2013-01-18T14:02:42.718Z[Europe/London]
Expected: match a condition
     but: was <2013-01-18T14:02:42.718Z[Europe/London]>

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at uk.gov.justice.services.test.utils.core.helper.TypeCheck.verify(TypeCheck.java:60)
	at

**Comment by purple52** [comment]
Closed by #31
